[package]
name = "agent-stock-basket"
version = "0.1.0"
description = "Auto-Rebalancing Vault RWA Stock Basket"
edition = "2021"

[package.metadata.solana]
os-dependent-build = false
sbpf-version = "v3"

[lib]
crate-type = ["cdylib", "rlib"]
name = "agent_stock_basket"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "=0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "=0.31.1" }
pyth-sdk-solana = "0.10.6"
solana-program = "=2.3.0"
